version: "2.4"

services:
  mssql-init-coveo:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-xp1-mssql-init-coveo:509713-${SITECORE_VERSION}
    build:
      context: ./docker/build/mssql-init
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xp1-mssql-init:${SITECORE_VERSION}
        MODULE_ASSETS: sitecore101.azurecr.io/community/modules/custom-coveo509713-assets
        MODULE_NAME: coveo
    scale: 0
